server.port: 8082
spring:
 jpa:
  hibernate.ddl-auto: update
  properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
 datasource:
  url: jdbc:mysql://localhost:3306/shopping_list?serverTimezone=UTC
  username: shopping_list
  password: shopping_list
